name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      replit_url:
        description: 'Replit App URL (leave empty for default)'
        required: false
        default: 'https://stickmananimations.replit.app'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Update Replit URL if provided
        if: github.event.inputs.replit_url != ''
        run: |
          # Replace the Replit URL in index.js with the provided one
          sed -i "s|https://stickmananimations.replit.app|${{ github.event.inputs.replit_url }}|g" pages/index.js
          
      - name: Update API proxy URL if needed
        if: github.event.inputs.replit_url != ''
        run: |
          # Extract the hostname from the URL and create API URL
          REPLIT_HOST=$(echo "${{ github.event.inputs.replit_url }}" | sed -e 's|^https://||' -e 's|/.*$||')
          REPLIT_API_URL="https://${REPLIT_HOST}/api/:path*"
          # Replace the API URL in vercel.json
          sed -i "s|https://stickmananimations-api.replit.app/api/:path*|${REPLIT_API_URL}|g" vercel.json
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}